---
title: "Lab 05 - La Quinta is Spanish for next to Denny's, Pt. 2"
author: "Yuxin Xie"
date: "2/13/2025"
output: github_document
---

# install.packages("devtools")
#devtools::install_github("rstudio-education/dsbox")

### Load packages and data

```{r load-packages, message = FALSE}

library(tidyverse) 
library(dsbox) 
```

```{r load-data, message = FALSE}
states <- read_csv("data/states.csv")
dn <- dsbox::dennys
lq <- dsbox::laquinta
```

### Exercise 1
```{r How many Denny’s locations are there in Alaska}
dn_ak <- dn %>%
  filter(state == "AK")
nrow(dn_ak)
## There are 3 Denny’s locations in Alaska.

lq_ak <- lq %>%
  filter(state == "AK")
nrow(lq_ak)
## There are 2 La Quinta locations in Alaska.
```

### Exercise 2
```{r pairings}
## There are 6 pairings we need to calculate 
```

### Exercise 3
```{r join}
#?full_join
dn_lq_ak <- full_join(dn_ak, lq_ak, 
                      by = "state")
dn_lq_ak
```

### Exercise 4
```{r observations}
## there are 6 observations in the joined dn_lq_ak data frame. There are 11 variabels. 
```

### Exercise 5
```{r distances}
##One way of calculating the distance between any two points on the earth is to use the Haversine distance formula. This formula takes into account the fact that the earth is not flat, but instead spherical.
## This function is not available in R, but we can save the following function to a file called haversine.R that we can load and then use:

haversine <- function(long1, lat1, long2, lat2, round = 3) {
  # convert to radians
  long1 <- long1 * pi / 180
  lat1 <- lat1 * pi / 180
  long2 <- long2 * pi / 180
  lat2 <- lat2 * pi / 180

  R <- 6371 # Earth mean radius in km

  a <- sin((lat2 - lat1) / 2)^2 + cos(lat1) * cos(lat2) * sin((long2 - long1) / 2)^2
  d <- R * 2 * asin(sqrt(a))

  return(round(d, round)) # distance in km
}
```

### Exercise 6
```{r calculate the distances}
dn_lq_ak <- dn_lq_ak %>%
  mutate (distance = haversine (longitude.x, latitude.x, longitude.y,  latitude.y, round =3))

print (dn_lq_ak$distance)
```

### Exercise 7
```{r minimum distance between a Denny’s and La Quinta for each Denny’s location}
dn_lq_ak_mindist <- dn_lq_ak %>%
  group_by(address.x) %>%
  summarize(closest = min(distance))
dn_lq_ak_mindist
```

### Exercise 8
```{r distribution}
summary(dn_lq_ak_mindist$closest)

ggplot(dn_lq_ak_mindist, aes(x = reorder(address.x, closest), y = closest)) +
  geom_bar(stat = "identity", fill = "pink", alpha = 0.7) +
  labs(title = "Distance from Denny's to Nearest La Quinta in Alaska",
       x = "Denny's Location",
       y = "Distance") +
  theme_minimal()
## from each Denny's to its nearest La Quinta in Alaska is within 6 km.
## min is 2.035km, max = 5.998km, on average, the distance from Denny's to its nearest La Quinta in Alaska is 4.41km. 
```

### Exercise 9 (1)
```{r Repeat the same analysis for North Carolina}
#1 filter Denny’s and La Quinta Data Frames for NC,
dn_nc <- dn %>%
  filter(state == "NC")
nrow(dn_nc)
## There are 28 Denny’s locations in NC.

lq_nc <- lq %>%
  filter(state == "NC")
nrow(lq_nc)
## There are 12 La Quinta locations in NC.
```

### Exercise 9 (2)
```{r Repeat the same analysis for North Carolina}
#2 join these data frames to get a complete list of all possible pairings
dn_lq_nc <- full_join(dn_nc, lq_nc, 
                      by = "state")
dn_lq_nc
nrow(dn_lq_nc)
## there are 336 pairings 
```

### Exercise 9 (3)
```{r Repeat the same analysis for North Carolina}
#3 calculate the distances between all possible pairings of Denny’s and La Quinta in NC
dn_lq_nc <- dn_lq_nc %>%
  mutate (distance = haversine (longitude.x, latitude.x, longitude.y,  latitude.y, round =3))

print (dn_lq_nc$distance)
```

### Exercise 9 (4)
```{r Repeat the same analysis for North Carolina}
#4 find the minimum distance between each Denny’s and La Quinta location
dn_lq_nc_mindist <- dn_lq_nc %>%
  group_by(address.x) %>%
  summarize(closest = min(distance))
dn_lq_nc_mindist
```

### Exercise 9 (5)
```{r Repeat the same analysis for North Carolina}
#5 visualize and describe the distribution of these shortest distances using appropriate summary statistics.
summary(dn_lq_nc_mindist$closest)

ggplot(dn_lq_nc_mindist, aes(x = reorder(address.x, closest), y = closest)) +
  geom_bar(stat = "identity", fill = "green", alpha = 0.7) +
  labs(title = "Distance from Denny's to Nearest La Quinta in NC",
       x = "Denny's Location",
       y = "Distance") +
  theme_minimal()
## from each Denny's to its nearest La Quinta in NC 
## min is 1.779km, max = 187.935km, on average, the distance from Denny's to its nearest La Quinta in NC is 65.444km. 
```


### Exercise 10 (1)
```{r Repeat the same analysis for Texas}
#1 filter Denny’s and La Quinta Data Frames for TX,
dn_tx <- dn %>%
  filter(state == "TX")
nrow(dn_tx)
## There are 200 Denny’s locations in TX.

lq_tx <- lq %>%
  filter(state == "TX")
nrow(lq_tx)
## There are 237 La Quinta locations in TX.
```

### Exercise 10 (2)
```{r Repeat the same analysis for TX}
#2 join these data frames to get a complete list of all possible pairings
dn_lq_tx <- full_join(dn_tx, lq_tx, 
                      by = "state")
dn_lq_tx
nrow(dn_lq_tx)
## there are 47400 pairings 
```

### Exercise 10 (3)
```{r Repeat the same analysis for TX}
#3 calculate the distances between all possible pairings of Denny’s and La Quinta in TX
dn_lq_tx <- dn_lq_tx %>%
  mutate (distance = haversine (longitude.x, latitude.x, longitude.y,  latitude.y, round =3))
```

### Exercise 10 (4)
```{r Repeat the same analysis for TX}
#4 find the minimum distance between each Denny’s and La Quinta location
dn_lq_tx_mindist <- dn_lq_tx %>%
  group_by(address.x) %>%
  summarize(closest = min(distance))
```

### Exercise 9 (5)
```{r Repeat the same analysis for TX}
#5 visualize and describe the distribution of these shortest distances using appropriate summary statistics.
summary(dn_lq_tx_mindist$closest)

ggplot(dn_lq_tx_mindist, aes(x = reorder(address.x, closest), y = closest)) +
  geom_bar(stat = "identity", fill = "purple", alpha = 0.7) +
  labs(title = "Distance from Denny's to Nearest La Quinta in TX",
       x = "Denny's Location",
       y = "Distance") +
  theme_minimal()
## from each Denny's to its nearest La Quinta in TX 
## min is 0.016km, max = 60.582km, on average, the distance from Denny's to its nearest La Quinta in TX is 5.7918km. 
```


### Exercise 11 (1)
```{r Repeat the same analysis for MN}
#1 filter Denny’s and La Quinta Data Frames for MN,
dn_MN <- dn %>%
  filter(state == "MN")
nrow(dn_MN)
## There are 15 Denny’s locations in MN.

lq_MN <- lq %>%
  filter(state == "MN")
nrow(lq_MN)
## There are 7 La Quinta locations in MN.
```

### Exercise 11 (2)
```{r Repeat the same analysis for MN}
#2 join these data frames to get a complete list of all possible pairings
dn_lq_MN <- full_join(dn_MN, lq_MN, 
                      by = "state")
dn_lq_MN
nrow(dn_lq_MN)
## there are 105 pairings 
```

### Exercise 11 (3)
```{r Repeat the same analysis for MN}
#3 calculate the distances between all possible pairings of Denny’s and La Quinta in MN
dn_lq_MN <- dn_lq_MN %>%
  mutate (distance = haversine (longitude.x, latitude.x, longitude.y,  latitude.y, round =3))
```

### Exercise 11 (4)
```{r Repeat the same analysis for MN}
#4 find the minimum distance between each Denny’s and La Quinta location
dn_lq_MN_mindist <- dn_lq_MN %>%
  group_by(address.x) %>%
  summarize(closest = min(distance))
dn_lq_MN_mindist
```

### Exercise 11 (5)
```{r Repeat the same analysis for MN}
#5 visualize and describe the distribution of these shortest distances using appropriate summary statistics.
summary(dn_lq_MN_mindist$closest)

ggplot(dn_lq_MN_mindist, aes(x = reorder(address.x, closest), y = closest)) +
  geom_bar(stat = "identity", fill = "yellow", alpha = 0.7) +
  labs(title = "Distance from Denny's to Nearest La Quinta in MN",
       x = "Denny's Location",
       y = "Distance") +
  theme_minimal()
## from each Denny's to its nearest La Quinta in MN 
## min is 1.074km, max = 56.63km, on average, the distance from Denny's to its nearest La Quinta in MN is 13.19km. 
```

### Exercise 12
```{r }

```


